# Small model configuration for quick experimentation
model:
  vocab_size: 32000
  d_model: 256
  n_heads: 4
  n_layers: 4
  d_ff: 1024
  max_seq_len: 512
  dropout: 0.1
  attention_dropout: 0.1
  activation: "gelu"
  pre_norm: true

training:
  batch_size: 16
  learning_rate: 5e-4
  weight_decay: 0.01
  num_epochs: 5
  lr_scheduler: "cosine"
  warmup_steps: 500
  optimizer: "adamw"
  gradient_accumulation_steps: 2
  use_amp: true
  save_steps: 1000
  eval_steps: 500
  logging_steps: 50

data:
  dataset_name: "wikitext"
  dataset_config: "wikitext-2-raw-v1"
  max_length: 512
  vocab_size: 32000
  pack_sequences: true
